name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_ACCESSTOKEN }}
    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v5
      with: 
        context: .
        push: true
        tags: kuzinvadym/react-docker-demo:latest, kuzinvadym/react-docker-demo:${{ github.sha }}
        build-args: |
          "REACT_APP_BACKEND_HOST=backend-service"
          "REACT_APP_APP_VERSION=V1"